[pymultinotifier]

[db_manager]
database_file_name = "db.sqlite3"
# working_dir = ""
# database_url = ""

[discord]
web_hook=""

[telegram]
token=""
chat_id=""

[twitter]
consumer_key=""
consumer_secret=""
access_token=""
access_token_secret=""