"""add_profile_platform_post_tables

Revision ID: 54411488da94
Revises: 
Create Date: 2022-11-12 05:00:46.172837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54411488da94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile'))
    )
    op.create_table('platform',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('platform_type', sa.Enum('DISCORD', 'TELEGRAM', 'TWITTER', name='platformtype'), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_platform_profile_id_profile'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform'))
    )
    op.create_table('post',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name=op.f('fk_post_platform_id_platform'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('platform')
    op.drop_table('profile')
    # ### end Alembic commands ###
