"""add_credentials_column_to_platform

Revision ID: 5df4fc2ae663
Revises: 54411488da94
Create Date: 2022-11-13 04:16:34.302235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df4fc2ae663'
down_revision = '54411488da94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform', sa.Column('credentials', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform', 'credentials')
    # ### end Alembic commands ###
